package org.uniweaver.scheduling.domain;

import java.util.List;

import ai.timefold.solver.core.api.domain.entity.PlanningEntity;
import ai.timefold.solver.core.api.domain.lookup.PlanningId;
import ai.timefold.solver.core.api.domain.valuerange.ValueRangeProvider;
import ai.timefold.solver.core.api.domain.variable.PlanningVariable;

/**
 * The planning entity. One instance = one occurrence of one MODULE's unit that a
 * given CLASS_ENTITY must attend once during the semester (there are
 * MODULE.unitsPerWeek of these per module+class pairing, generated by your app
 * before calling this service - sequenceIndex distinguishes them, e.g. for
 * minWeeksBetweenUnits/maxWeeksBetweenUnits-style spacing rules).
 * <p>
 * This is deliberately NOT a 1:1 mirror of SCHEDULE_ENTRY. SCHEDULE_ENTRY stores
 * *arrays* of moduleIds/roomIds/classIds/lecturerIds because one calendar slot can
 * bundle several of each (e.g. a joint lecture across two classes). A solver wants
 * one atomic decision per entity, so here each SessionAssignment is scheduled
 * independently; your app is then free to fold any SessionAssignments that land on
 * the same room + timeSlot + lecturer back into a single SCHEDULE_ENTRY row for
 * storage (or just store each as its own SCHEDULE_ENTRY with single-element arrays -
 * both are valid, pick whichever matches how "joint sessions" are meant to work).
 * <p>
 * Lecturer qualification (MODULE }o--o{ LECTURER "taught by") is enforced by
 * restricting lecturerCandidates to the qualified pool up front (see
 * getLecturerCandidates below) rather than by a constraint - the solver can
 * physically never pick an unqualified lecturer.
 */
@PlanningEntity
public class SessionAssignment {

    @PlanningId
    private String id;

    // ---- fixed problem facts, set once before solving and never changed by the solver ----
    private String moduleId;
    private String moduleName;
    private String classId;
    private String className;
    private int studentCount;
    private int durationMinutes;
    private int sequenceIndex;
    private List<Lecturer> lecturerCandidates;

    // ---- planning variables: what the solver decides ----
    private TimeSlot timeSlot;
    private Room room;
    private Lecturer lecturer;

    public SessionAssignment() {
    }

    public SessionAssignment(String id, String moduleId, String moduleName, String classId, String className,
            int studentCount, int durationMinutes, int sequenceIndex, List<Lecturer> lecturerCandidates) {
        this.id = id;
        this.moduleId = moduleId;
        this.moduleName = moduleName;
        this.classId = classId;
        this.className = className;
        this.studentCount = studentCount;
        this.durationMinutes = durationMinutes;
        this.sequenceIndex = sequenceIndex;
        this.lecturerCandidates = lecturerCandidates;
    }

    public boolean isFullyAssigned() {
        return timeSlot != null && room != null && lecturer != null;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getModuleId() {
        return moduleId;
    }

    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }

    public String getModuleName() {
        return moduleName;
    }

    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    public String getClassId() {
        return classId;
    }

    public void setClassId(String classId) {
        this.classId = classId;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public int getStudentCount() {
        return studentCount;
    }

    public void setStudentCount(int studentCount) {
        this.studentCount = studentCount;
    }

    public int getDurationMinutes() {
        return durationMinutes;
    }

    public void setDurationMinutes(int durationMinutes) {
        this.durationMinutes = durationMinutes;
    }

    public int getSequenceIndex() {
        return sequenceIndex;
    }

    public void setSequenceIndex(int sequenceIndex) {
        this.sequenceIndex = sequenceIndex;
    }

    /** Per-entity value range: restricts the lecturer variable to this session's qualified pool. */
    @ValueRangeProvider(id = "lecturerRange")
    public List<Lecturer> getLecturerCandidates() {
        return lecturerCandidates;
    }

    public void setLecturerCandidates(List<Lecturer> lecturerCandidates) {
        this.lecturerCandidates = lecturerCandidates;
    }

    @PlanningVariable(valueRangeProviderRefs = "timeSlotRange")
    public TimeSlot getTimeSlot() {
        return timeSlot;
    }

    public void setTimeSlot(TimeSlot timeSlot) {
        this.timeSlot = timeSlot;
    }

    @PlanningVariable(valueRangeProviderRefs = "roomRange")
    public Room getRoom() {
        return room;
    }

    public void setRoom(Room room) {
        this.room = room;
    }

    @PlanningVariable(valueRangeProviderRefs = "lecturerRange")
    public Lecturer getLecturer() {
        return lecturer;
    }

    public void setLecturer(Lecturer lecturer) {
        this.lecturer = lecturer;
    }

    @Override
    public String toString() {
        return moduleName + " / " + className + " #" + sequenceIndex;
    }
}
